#!/usr/bin/env python3
"""
Claude Code Generator Script
Generates code based on GitHub issue descriptions using Claude AI
"""

import os
import re
import json
import sys
from pathlib import Path
import anthropic

def get_issue_context():
    """Extract issue title and body from environment variables"""
    issue_title = os.environ.get('ISSUE_TITLE', '')
    issue_body = os.environ.get('ISSUE_BODY', '')
    return issue_title, issue_body

def generate_code_with_claude(issue_title: str, issue_body: str) -> dict:
    """Call Claude API to generate code based on issue description"""
    
    client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
    
    prompt = f"""You are a web developer helping to build a website for "Mrittika By Kanak" - a handmade clay gifts business.

Issue Title: {issue_title}
Issue Description: {issue_body}

Based on this request, generate the appropriate HTML, CSS, and/or JavaScript code.

Requirements:
1. The website is about handmade clay gifts
2. Keep the existing design style consistent (modern, clean)
3. Generate complete, production-ready code
4. Include comments in the code
5. Make it responsive for mobile devices
6. Return the code in a format that can be directly used

Please provide:
1. The complete code (HTML/CSS/JS as needed)
2. Which file(s) to update (e.g., index.html, styles.css)
3. Brief description of changes

Format your response as JSON:
{{
    "files": [
        {{
            "path": "path/to/file",
            "content": "full file content here"
        }}
    ],
    "summary": "Brief description of changes"
}}
"""
    
    message = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=4096,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )
    
    response_text = message.content[0].text
    
    # Extract JSON from response
    json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
    if json_match:
        try:
            result = json.loads(json_match.group())
            return result
        except json.JSONDecodeError:
            return {
                "files": [],
                "summary": "Could not parse Claude response",
                "raw_response": response_text
            }
    
    return {
        "files": [],
        "summary": "Could not extract code from Claude response",
        "raw_response": response_text
    }

def apply_changes(changes: dict) -> bool:
    """Apply generated code changes to repository files"""
    
    try:
        for file_info in changes.get('files', []):
            file_path = file_info.get('path')
            content = file_info.get('content')
            
            if not file_path or not content:
                continue
            
            # Create directory if needed
            Path(file_path).parent.mkdir(parents=True, exist_ok=True)
            
            # Write file
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"✅ Updated: {file_path}")
        
        return True
    except Exception as e:
        print(f"❌ Error applying changes: {e}")
        return False

def main():
    """Main execution"""
    
    print("🤖 Claude Code Generator Starting...")
    
    # Get issue context
    issue_title, issue_body = get_issue_context()
    
    if not issue_title:
        print("❌ No issue title found")
        sys.exit(0)
    
    print(f"📝 Issue: {issue_title}")
    
    # Generate code with Claude
    print("🔄 Calling Claude AI...")
    changes = generate_code_with_claude(issue_title, issue_body)
    
    if not changes.get('files'):
        print("⚠️ No code generated")
        print("::set-output name=code_generated::false")
        sys.exit(0)
    
    print(f"✨ Generated code for {len(changes['files'])} file(s)")
    
    # Apply changes
    print("💾 Applying changes...")
    if apply_changes(changes):
        print("✅ Changes applied successfully!")
        
        # Output for GitHub Actions
        summary = changes.get('summary', 'Code generated by Claude')
        print(f"::set-output name=code_generated::true")
        print(f"::set-output name=changes_summary::{summary}")
    else:
        print("❌ Failed to apply changes")
        print("::set-output name=code_generated::false")

if __name__ == "__main__":
    main()
